
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  # name: your-registered-name
  version: '0.1'
  summary: Determine what the license plate says about vehicles' origins
  description: |
    The numbers and letters on various license plates aren't arbitrary.
    They provide information regarding the vehicle's origins, often
    where the license plate was issued. PlateCodes lets you regex-search
    for this information to determine things like what province a vehicle
    is from or what embassy it's from.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
