  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: platecodes-linux
  version: '0.1'
  summary: Determine what the license plate says about vehicles' origins
  description: |
    The numbers and letters on various license plates aren't arbitrary.
    They provide information regarding the vehicle's origins, often
    where the license plate was issued. PlateCodes lets you regex-search
    for this information to determine things like what province a vehicle
    is from or what embassy it's from.

  grade: stable
  confinement: devmode

  parts:
    qml:
      plugin: qmake
    platecodes:
      plugin: copy
      files:
        main.qml: Main.qml
